"""Increase password column length

Revision ID: 440213da2a01
Revises: c27fba6f8b3f
Create Date: 2025-01-02 08:47:56.924439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440213da2a01'
down_revision = 'c27fba6f8b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
