"""Add type_of to transactions

Revision ID: b4e96e7c5b7a
Revises: c6b30348854d
Create Date: 2025-01-08 10:46:23.253129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e96e7c5b7a'
down_revision = 'c6b30348854d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('type_of', sa.String(length=10), nullable=False, server_default='Expenses'))
    op.execute('ALTER TABLE transactions ALTER COLUMN type_of DROP DEFAULT')  # Remove the default if not needed.


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('type_of')

    # ### end Alembic commands ###
